site_name: Marco Bassetto
site_url: https://m-bassetto.github.io/
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.top
    - search.highlight

hide:
  - toc

nav:
  - Home: index.md
  - Curriculum Vitae: files/cv.pdf
  - Research: 
    - Full List: research/research.md
    - Government Policy Design: research/design.md
    - Political Economy and Optimal Taxation: research/political.md
    - Expository Pieces: research/expository.md
    - Miscellaneous Topics: research/misc.md
